name: Trigger Both Bots

on:
  workflow_dispatch:

jobs:
  trigger_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger bot.yml
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'bot.yml',
              ref: context.ref.replace('refs/heads/', ''),
            })
      - name: Trigger bullet_bot.yml
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'bullet_bot.yml',
              ref: context.ref.replace('refs/heads/', ''),
            })
